### ISSUE TITLE
Unable to properly start the experimental portable Lutris installer

### ISSUE THREAD

**Issue by AshenPaladin** [leycec/aokana-linux#2]
Attempting to follow the instructions and start the experimental portable Lutris installer does not work - it does properly launch Lutris, but the installation window inside Lutris is empty and shows no options that would allow me to go forward. I will attach an image of the window and I copied the what the terminal is showing me into a text file, since it does show an error right at the end.

[Lutrisportablerror.txt](https://github.com/leycec/aokana-linux/files/5566796/Lutrisportablerror.txt)
![Screenshot from 2020-11-19 14-46-33](https://user-images.githubusercontent.com/64322403/99668622-ab194680-2a76-11eb-846a-c86f17f99904.png)

**Comment by leycec** [comment]
**Fascinating...** and depressing! That's definitely *not* the intended effect. :sob: 

Thanks so much for the explanatory screenshot, though. I'll play around with our portable installer for a bit and see if I can't reproduce this on my end. `</rolls_up_sleeves>`

Also, your GitHub avatar rocks. It's like the [Ourobouros](https://www.google.com/search?q=Ouroboros) had non-consensual relations with the [Celtic knot](https://www.google.com/search?q=celtic+knot) and made an illegitimate icon so stark and bleak that only die-hard Norwegian black metal aficionados could love.

**Comment by leycec** [comment]
**Bwaha!** Thanks to the detailed logfile you attached, I've successfully diagnosed the underlying issue. Thankfully, it's not us; it's Lutris 0.5.8, which released several days ago and which the logfile shows you're running. Specifically, it's the currently open lutris/lutris#3290 issue specific to Lutris 0.5.8 that you and numerous other end users are hitting. That's the "good" news. The bad news is that you'll now need to either:

* **Downgrade to an older Lutris version.** Unfortunately, [Lutris 0.5.7 *also* seems to suffer a similar issue](https://github.com/lutris/lutris/issues/3227). Yeah. I know, right? That said, I'm running Lutris 0.5.7.1 and can confirm this issue does *not* appear. If you're able to downgrade to either Lutris 0.5.7.1 or 0.5.6, that would be my first recommendation.
* **Wait until the next stable version of Lutris is released.** Unfortunately, Lutris doesn't release that frequently – so you're probably looking at a wait time of one to two months. Yeah. I know, right? I don't recommend patience, but sometimes we just have no choice but to suffer.

Unrelatedly, your PulseAudio configuration appears to be a bit munted. From the last line of that logfile:

```
[/etc/pulse/client.conf:3] Missing '='.
```

When you get a spare moment, you might want to take a look at line 3 of `/etc/pulse/client.conf` and try to resolve that. Thanks again for the detailed inquiry – and sorry I couldn't be of more gratifying assistance. :scream_cat:

**Comment by AshenPaladin** [comment]
Well, I'm actually quite surprised that you did answer, I wasn't even expecting that xD

I assumed that it was an issue with the installer and not with Lutris because all other games that I attempted to install through it did so without any issues, but I admittedly didn't try to use any other yml based installers and I also didn't think about checking for Lutris bugs, so sorry about it.

But thanks for looking into it. I'll try to see what I'd lose by downgrading, or just wait. It's a shame since I really wanted to give Aokana a try, but there are always visual novels to play I guess.

And thanks for that xD
I'm still a bit new to this entire Linux thing, I did have a few issues with PulseAudio and I probably did mess up something, I'll check that file and try to fix it.

And I do quite like my icon myself - it's supposed to be a stylised crown of thorns - I picked the original one up from a fantasy form and messed with it a little xD

**Comment by leycec** [comment]
> ...but there are always visual novels to play I guess.

**Excellent.** Rolling with life's punches is the secret ninjitsu technique to obtain happiness young. If you haven't already played the [original *Fate/stay night* (FSN)](https://vndb.org/v11) (...no Wikipedia links, because literally everything is a spoiler for this and most other visual novels), I also maintain a [related GitHub repository providing a one-click Lutris installer for *Fate/stay night \[Réalta Nua\] Ultimate Edition*, the definitive way to play *Fate/stay night* in 2020](https://github.com/leycec/fsnrnue).

You may now be thinking:

* "But... I can't use Lutris 0.5.8 to install stuff from the command-line, man?" Fortunately, you don't need to. Unlike this repository, the *Fate/stay night* Lutris installer hosted at that repository is entirely online – which means it's guaranteed to work for you without retriggering this issue. No command-line YML stuff required.
* "But... I don't even have *Fate/stay night*, man?" Fortunately, you don't need to. You can't actually buy *Fate/stay night* anywhere, which means it's abandonware, which means the only means of playing it is... **Yar, matey!** Yes, that's correct. We ride the high seas because we must, not because we want to. :pirate_flag:

I'm actually finishing up the third and final route of *Fate/stay night* on Linux as we speak. Needless to say, it is impeccable. I give it two crossed katanas way, way up. :crossed_swords: 

Also, I'm always adding new Lutris installers for masterclass [kamige](https://www.urbandictionary.com/define.php?term=kamige). Let me know if you have any personal requests. The [100-hour shounen mecha Japanese visual novel Baldr Sky](https://vndb.org/v1306) will probably be my next Big Big Project, unless the community has a better idea. Let's do this, bois!

>  I'm still a bit new to this entire Linux thing...

Welcome to Linux Land™, brave new OS traveller. Linux is increasingly the best place to experience esoteric Japanese visual novels from the eighties, nineties, and today – mostly thanks to Lutris, WINE, Steam Proton, and emulation support for ancient Japan-only gaming platforms like PC-9821 ([*Policenauts!*](https://en.wikipedia.org/wiki/Policenauts)) and MSX2 ([*Snatcher!*](https://en.wikipedia.org/wiki/Snatcher_(video_game))).

As a [hardcore back-to-terminal-basics Gentoo Linuxer](https://github.com/leycec/raiagent#raiagent--it-is-possibly-good-), I'd be delighted to answer any questions you might have about Linux in general, mainstream Linux distros like Ubuntu and Fedora, cult Linux distros like Arch or Gentoo, or... well, anything, really.

Lastly, since this issue appears to be upstream's fault, I'm closing this with apologies. But feel free to keep the conversation going or open a new issue if you have any further inquiries. Until then, enjoy your next visual novel and may the [moe](https://en.wikipedia.org/wiki/Moe_(slang)) be with you always. :fire:

**Comment by AshenPaladin** [comment]
I haven't played it yet, even if I extensively watched the anime adaptations - but ironically enough, I have already installed F/SN a few days ago without actually bothering to check the name and to realize that you're the maintainer of it too. I even specifically had to check the Github page because I faced that Script exception raised error, but following the instructions there allowed me to fix it. Thank you very much for creating that installer - I had managed to find the game for Windows, but it wouldn't just work for me on PlayonLinux and I had nearly given up on playing it on Linux until searching Lutris.

I'm also somewhat new as far as visual novels are concerned too, so I wouldn't have any personal requests yet, but I will be eagerly waiting any and all Lutris installers that you'd create for them. I went from playing no visual novels to having 10 or so installed and playing on Windows, so I'm more than happy to carry my newfound obsession with me over to Linux.

I but a newcomer in the Linux world, even if I've been repeatedly attempting to move over to Linux and abandon Windows for two to three years now. I am amazed by all the progress that was done, especially with Lutris and Proton, and I'm right on the edge of being able to use it full-time. I still have to dual-boot with Windows for now, and this is quite a headache since it messes with my workflow a little, but it's a worthy sacrifice.

I do have a question though it's more about Linux and its usage in general  - do you personally use Linux, or do you still use Windows one way or another? You're obviously quite experienced with Linux if you're using Gentoo - from my position as a mere Ubuntu user it looks like a completely different world, but it's the compatibility of programs that is the biggest issue from my perspective. So I'm a bit curious, are more experienced Linux users able to simply give up on Windows entirely (with the exception of Lutris and WINE of course), or do you still have it installed somewhere?

**Comment by leycec** [comment]
> I haven't played it yet, even if I extensively watched the anime adaptations...

**...this.** This hurts me. Actually, it hurts me less than I thought it would. The anime adaptions are shockingly well-done – especially both seasons of *Unlimited Blade Works* and the three God-tier *Heaven's Feel* films. The initial *Fate/stay night* series, though? I think we could have all lived without that.

So, you've been spoiled. That doesn't matter much for the first route (*Fate*) of the visual novel, which is so straightforward that there's not much to spoil there to begin with. However, that *definitely* matters for the second (*Unlimited Blade Works*) and third routes (*Heaven's Feel*), whose labyrinthine intertwined network of surprise cliffhanger twists really benefit from going in blind. Alas, to have watched anime first!

I still whole-heartedly recommended the visual novel. Just know that it won't hit those feels nearly as hard. :weary: 

If you do end up having a go at it, remember this if you remember anything of @leycec's incoherent gibberish: **collect all those sweet, sweet Tiger Dojo stamps.** Like many visual novels, *Fate/stay night* actively rewards 100% completionism – in this case, with awesome optional post-game content that you can only view by:

* Hunting **all of the BAD and DEAD ENDs** littered throughout the three routes. Since you're already spoiled, I whole-heartedly recommend [the official flowchart to chart your progress](http://jackk3000.intarbutt.info/datazz/FSN_Flowchart.pdf).
* After each BAD or DEAD END, **choosing to enter the Tiger Dojo.** This is technically optional, but there's no downside to entering the Tiger Dojo and a whole lotta upside (such as *hilarious* dialogue that makes me spew my evening coffee everywhere) – so you should *always* do it.

> Thank you very much for creating that installer...

You're most welcome. :full_moon_with_face: 

> I even specifically had to check the Github page because I faced that Script exception raised error, but following the instructions there allowed me to fix it.

So sorry about that. The next version of the *Ultimate Edition* installer should rectify all that nonsense. Sadly, the developers at [the Beast's Lair](https://forums.nrvnqsr.com) are currently in development hell and unable to release a stable update. **Urgh!**

> I went from playing no visual novels to having 10 or so installed and playing...

This fills me with unspeakable warmth. If you don't mind me rudely prying into your clandestine autobiography, what prompted you to take that first tentative step into the unhinged world of visual novels?

For me, it was the Gateway Drug to End All Gateway Drugs: **Persona 3.** Oh, how I loathed the 200 (!) procedurally-generated floors of the only dungeon (Tartarus) in that game. <sup>fuck tartarus.</sup> Oh, how I adored the visual novel-inspired "Social Link" virtual tourism of *totally-not* Todai (Tokyo University). When I finally accepted in the dankest pit of the darkest hour of the night that all I really wanted was the good parts of Persona 3 without the most loathsome dungeon crawl mankind has ever designed, I knew I'd developed a new baseless addiction that now needed continual feeding.

> ...do you personally use Linux, or do you still use Windows one way or another?

**Ah!** The Big Big Question. [My beautiful wife](https://allencenter.tufts.edu/our-team/alexis-pietak) (a research scientist) and I (a computer scientist) exclusively use Linux – with occasional dabbling into macOS as required by specific employers or clients. Neither of us have been molested by Windows for over a decade.

*My Nordic Gods... has it really been that long?*

> ...from my position as a mere Ubuntu user...

My wife's on Ubuntu as well! She loves it... and I love that, because I'd have to reluctantly stab my own eyes out if she wanted me to teach her Arch or Gentoo Linux. (Some things just ain't happening.)

> ...it's the compatibility of programs that is the biggest issue from my perspective.

**Absolutely.** That's most newcomer's beef with Linux and justifiably so. In my beautiful wife's case, she's fortunate in that most scientific software actually runs better (i.e., stabler, faster, deeper, harder) on Linux and macOS than on Windows. The only non-scientific workplace software she regularly interfaces with are:

* Microsoft Teams (recently ported to Linux, bizarrely).
* Microsoft Office (trivially replaced with [LibreOffice](https://www.libreoffice.org)).
* Adobe Photoshop (trivially replaced with [GIMP](https://www.gimp.org)).
* Adobe Premier (trivially replaced with [Kdenlive](https://kdenlive.org)).
* Adobe Illustrator (trivially replaced with [Inkscape](https://inkscape.org)).

In my case, I self-select for Linux-friendly employment. Employers and clients requiring proprietary Microsoft products (e.g., Visual Studio) and proprietary Microsoft languages (e.g., C#, F#) are a strict **no-go** for both of us. We have the luxury to be picky, though. We live in a nondescript cottage on a little-known lake in the vast, unbridled emptiness of the Canadian wilderness. Unlike most software engineers handcuffed to the nearest urban cubicle farm, we don't have to worry about being forcibly evicted at gunpoint from the closet space we're currently sharing with three unpaid interns if we fail to promptly use a Microsoft-only product at work.

I guess what I'm saying is this. The post-COVID-19 world desperately needs a [global Universal Basic Income (UBI)](https://www.reddit.com/r/BasicIncome) to ensure that everyone on Planet Earth has the right to say "Hell, no!" to unfavourable, discriminatory, exploitive workplace conditions. *But that's just, like, my opinion, man.*

But don't sweat the dual-booting. There's no shame in business realities. *Everyone* dual-boots back into the warm, familiar, soothing corporate glow of the Windows 10 tiling Metro UI when they first begin "transitioning" into the cold, unfamiliar, anxiety-provoking lair of volunteer depravity and unpaid idealism that is the Ubuntu 20.04 GNOME Shell UI.

Take as much time as you need. Linux will always be there, stealthily breathing into your ear like some creepy [ASMR](https://en.wikipedia.org/wiki/ASMR) Twitch streamer on a non-profit 24-hour bender for the rectal cyst charity run by her delinquent father.

**Comment by AshenPaladin** [comment]
I did ironically enough start with the initial Fate stay/night adaptation and I powered through it just in order to get the story, being allured by the promise of the better adaptations that followed and not wanting to miss the first route. UBW was absolutely incredible and I absolutely loved it - but what I said might have been a little misleading, in that I haven't actually watched the Heaven's Feel movies yet. I did receive spoilers from friends unfortunately, so I know a few rough points especially considering Sakura, and that is also why I haven't watched the movies yet - I want to watch them all in one sitting, back to back, so as to minimise the suffering and the feels to levels that I can handle.

I will however certainly play the visual novel even if I've already been spoiled with a lot of its content - I love the story and the characters just too much not to do it xD

Thanks for the tip though! I haven't actually read that much about the visual novel itself so I was going to jump into it blindly. I've never heard of Tiger Dojo stamps before, but I will be careful about them. I was indeed planning to do all the routes however - I tend to be a bit of a completionist.

As for the installer, don't worry about it, even just having it is incredibly helpful - and following the instructions to fix that particular bug were very easy!

As for my entrance in the visual novel world, I was always somewhat on the edge of it, due to my extensive watching of anime. I never actually played one however until a friend of mine recommended me to try a free visual novel called Katawa Shoujo, which I installed and then played for days. I loved the story and the characters, and by the time I finished it, I was already deep inside the visual novel world and I had also discovered a new addiction xD

From there I started to consistently play them, even if my free time never allows me to play as many as I would want to. Persona is one of the series that I really, really want to get into, even if that is mostly because of me watching Persona 5 playthroughs on YouTube, but it being a console game never allowed me to. I did however attempt to install Persona 3 with the help of a PSP emulator on Windows around a year ago but it failed for a reason that I don't remember, and I was seriously considering buying Persona 4 now that it appeared on Windows, it's been sitting in my Steam Wishlist for a while xD

A decade without Windows sounds absolutely amazing, even if I barely have more than a decade of Windows use under my belt. I have an incredibly hate filled relationship with Windows especially since the first laptop I bought with my own money and thought of as my own was one that came with Windows 8. It's been years now since I've been trying to escape Windows' grasp, but I just never quite manage to.

I quite enjoy Ubuntu because it is quite simple and it's consistently been the distro I tried to escape too, but sooner or later I try to do something that I probably shouldn't mess with without knowing what I'm doing and I end up having to nuke my entire installation. Just now a game that I was playing started crashing and taking my entire system down with it, so I tried to reinstall it Ubuntu entirely only to be met with a bug in the installer that causes it to fail.

I love Linux, and I truly believe that one day I will be able to use it solely, but sometimes it can just be very frustrating, and that's why I'm trying to also keep Windows installed alongside it.

Ironically enough, if I were to use my computer only for university related work I would have no issues in just using Linux full-time. In this era of quarantines and online courses I've been using Microsoft Teams and Google Meet, both of which work. I already use GIMP full time even on Windows, and I've been using SoftMaker Office mostly because of its design and because of my unwillingness to pay for an Office 365 subscription.

But it's games and gaming that will forever be my doom here. Linux has done tremendous progress over the past two years - I can now play at least roughly half of all my games here, and ironically enough, even some who run in Proton run much better here than on Windows, but there will forever be games that will only be playable on Windows. I am eagerly hoping for a fix relating anti-cheat in Proton/WINE however, and that I think would be a moment that would allow me to move nearly full-time to Ubuntu.

It is however always nice to find out that there are people who are fully able to use Linux without any issues - it's somewhat comforting, and it makes me feel like the age of Microsoft dominance won't last forever. And Linux being there in the background is just as comforting - it's good to know that there is an alternative to Windows. I am a bit worried about whether Linux will be able to maintain the pace of its current gaming-related progress however, which is why I've been putting even more effort than before into actually using Linux.

As for the UBI, it always sounded like a very good and overall pretty pragmatic idea to me, but I don't know if there will even be nations adopting such a program, let alone the the world as a whole.

**Comment by leycec** [comment]
**Wow!** Thanks a Eurozone-standardized metric tonne for that deep dive. I've been... preoccupied with [yet *another* dangerous open-source time sink](https://github.com/beartype/beartype), insufferable (but loving) Holiday gift preparations, and crushing outbreaks of the Global Pandemic to End All Global Pandemics here in the local Kingston area. My wife and I are both immunocompromised – so let's keep those lucky fingers crossed, people. :crossed_fingers: 

> UBW was absolutely incredible and I absolutely loved it...

*Right?* Western media never touches those genre tags with a ten-foot rat-catching pole, which leaves Asia free to clean up the literary sphere on hot topics like `[insert-spoiler]`. Actually... that's not entirely factual. "Groundhog Day" and "Edge of Tomorrow" both invest hard in that topic and I loved them dearly for it. But, in general, we've gone all-in as a hegemonic global culture on the standard Judeochristian linear conception of Time, Industrial Progress, and Penultimate Existence. **Booooring.**

That's the trouble with UBW, though. You do not publicly talk about UBW for fear of spoiling someone else's good time. Who knows what innocent bystanders could be lurking about...

> ...I haven't actually watched the Heaven's Feel movies yet.

*Yay!* Fist bumps all around.

> I did receive spoilers from friends unfortunately...

*Boo!* Fists to the heads of Those Who Spoil Fun.

> ...so I know a few rough points especially considering Sakura.

This upsets me. I now need an oxygen bag. You do not spoil Sakura. When will humanity ever learn?

> I want to watch them all in one sitting, back to back, so as to minimise the suffering and the feels to levels that I can handle.

**Yes.** This is the Way of Emptiness. Suffering that cannot be contained must be contained in a single evening with gratuitous tubs of Pralines and Cream and/or Cookie Dough ice cream. (*Take as needed for pain.*)

> I've never heard of Tiger Dojo stamps before...

*heh heh*

As with most adventures in life, I advise reading as little about it beforehand as possible. Just know that the official flowchart PDF is now your special friend.

> Katawa Shoujo

*classic feels*

> I was seriously considering buying Persona 4 now that it appeared on Windows...

**Oh. Oh. Ohhhhhhhh.** If I had the spare change, I'd happily gift you a glorious Christmas Santa-style Steam copy of P4:G. Sadly, physical reality, my hollow wallet, and my adoring wife would all have unpleasant things to say about that.

Do it someday! The gameplay is merely acceptable-tier, but the pristine background setting (*Japanese inaka, bro*), flavourful overarching narrative, and exceptional waifus and/or husbandos make P4:G the JRPG pinnacle of Atlus. P5:R also rocks, but it's a bit more of a tepid 80's Dad rock spectacle by compare to the illustrious rural slow-burn pagentry of P4:G.

> Just now a game that I was playing started crashing and taking my entire system down with it, so I tried to reinstall it Ubuntu entirely only to be met with a bug in the installer that causes it to fail.

That... that's a rough take there. Ouch. *Cries in reinstallation woes.*

My wife's assorted and sundry Ubuntu machines run mostly flawless – until the inevitable upgrade to the next Long-Term Support (LTS). Then things stereotypically blow up with a catastrophic sonic boom. Not a single upgrade has gone by without me rolling up the ice-encrusted Canadian sleeves and getting dirty with the low-level terminal hackery – which I am more than delighted to do, of course. But monochrome green text on a black background ain't everyone's idea of a fun Saturday night out.

My Ubuntu advice for preserving sanity and Saturday nights is:

* **Keep `/home` on a separate partition.** Then when things inevitably blow up in the next poorly bug-tested upgrade, you don't lose anything meaningful when you wipe and reinstall. (*You prolly already do this, so... just throwing that out there.*)
* **Avoid [Personal Package Archives (PPAs)](https://help.launchpad.net/Packaging/PPA) as much as feasible.** They make upgrades *pure vitriolic Hell,* which you do not need in your life. Use [snaps](https://en.wikipedia.org/wiki/Snap_\(package_manager\)) or [simple deb files](https://itsfoss.com/install-deb-files-ubuntu) instead if you ever need third-party packages outside the official Ubuntu repos. (*You prolly already do this, so... just throwing that out there.*)

## But Wait, There's More

Oh, and I'm reopening this. `</sigh>`

For inexplicable and infuriating reasons, Lutris developers intentionally broke backward compatibility in their YAML file format with Lutris 0.5.8. That sucks. They then verbally attacked, minimized, and invalidated everyone who complained about this dismal state of affairs. That *really* sucks.

They've made their problem everyone else's problem, so it's sadly up to me to resolve this on our end by refactoring the YAML files hosted at this repository to conform to their new file format. *What a waste of my precious bodily fluids.*

I still adore Lutris as software, but the customer service leaves something to be desired. Let's do this folks! I should have working Aokana Lutris scripts committed in a day or so.

— more geriatric elderly Millenial "wisdom" and soon-to-be-working Aokana Lutris scripts to come!

**Comment by leycec** [comment]
**Boom!** I've patched up all our Aokana scripts to conform to the new YAML file format required by Lutris ≥ 0.5.8. Would you mind giving one or all of them a try and reporting back? Also, did I mention you're awesome? 'cause... I should probably mention that.

I should also mention that Aokana is **absolutely hilarious.** Whenever *any* of those lead heroines open their adorable little mouths with yet another ludicrous one-liner, I can't help but bust a gut all over the monitor. Also: the CG is impeccable, the animations are outrageous, and the OP is a right banger. My only regret is that the MC himself isn't voiced. I don't really do that *self-insert* thing like most Japanese VN readers. I mean, I get budgetary constraints and all, but... still. It's a mild bumber.

Don't sleep on this one, yo!

> As for the UBI, it always sounded like a very good and overall pretty pragmatic idea to me...

*Riiiiiiiight?*

> ...but I don't know if there will even be nations adopting such a program, let alone the the world as a whole.

**Bro.** The world's one step ahead of us all. [Spain is now the first industrialized nation to institutionalize a minimum income guarantee](https://www.ft.com/content/32730748-ef87-49e1-98b3-1d64cdab9df3), thanks to an unlikely partnership between Spain's [Socialist Workers' Party](https://en.wikipedia.org/wiki/Spanish_Socialist_Workers%27_Party) (i.e., the nation's oldest and most successful political party – so, effectively the equivalent of the Grand Old Party (GOP) in the United States, except at the exact opposite end of the left-right political spectrum) and... *COVID-19.*

Yup! Thanks to the worst public health crisis in human history, Spaniards now enjoy unconditional access to a minimum income of at least €461 Euros ($560 USD) per month. It's technically *not* a Universal Basic Income (UBI) in that those who earn above that minimum fail to receive anything except a stable, secure, and safe nation-state that has successfully eradicated poverty. Is that all? Still, it's only one incrementally small step from upgrading into a full-blown UBI – which I have no doubt it will do in the brutal decades to come.

Meanwhile here in Canada, all non-working working-age adults received an unconditional cash transfer of $2,000 CAD ($1,562 USD) per month for the eight-month duration of the Canadian Emergency Relief Benefit (CERB). Sadly, the CERB is no longer running. While it was, it was probably the most generous cash transfer from a government to its citizenry in human history.

With UBI now an official plank of the leading [Liberal Canadian Government](https://liberal.ca/policy-resolutions/97-basic-income-supplement-testing-dignified-approach-income-security-workingage-canadians), COVID-19 rapidly gestating across the pale ice-pocked flesh of the [Great White North](https://theculturetrip.com/north-america/canada/articles/why-is-canada-nicknamed-the-great-white-north), and [climate change vis-a-vis sea level rise now encroaching upon Canada's smallest province](https://projects.thestar.com/climate-change-canada/prince-edward-island), UBI seems all but a foregone conclusion here. It's no longer a matter of *if.* It's a matter of *when.* So probably several decades from now. `</shaking_my_head>`

At least *something* good happened in 2020. I'll take it.

## Would You Like to Know More?

I have a curmudgeonly wealth of command-line knowledge to transmit about low-level Linux fundamentals that *could* help you dodge bullets like needing to format and reinstall after games inevitably crash. Would that be beneficial? I'd rather not invest the maximum effort if you're already a stalwart CLI warrior. But... I suspect that's maybe not the case?

Lemme know and I'll drop the educational bomb below. Thanks again – and enjoy all the blessed Aokana goodies.

**Comment by imWatchful** [comment]
Sorry for writing in a closed issue but I can confirm that the `.yaml` error is fixed, the game installs and runs perfectly fine. (Tested on Lutris 0.5.8.1)
You could probably remove the warning in the `.yaml` files now :D, thanks for this project!

**Comment by leycec** [comment]
Oh, you're most welcome. Let me know if you have any further issues. Until then, enjoy all the high school hijinx of the antigraviton-fueled Flying Circus! :athletic_shoe:
